### ISSUE TITLE
Please show an example of setting the QoS Settings for 1 or more volumes

### ISSUE THREAD

**Issue by mmoore71** [solidfire/PowerShell#1]
I could use help writing a PowerShell script to set the QoS settings for 50 volumes. An example would be helpful.

**Comment by ghost** [comment]
#get all sf volumes and set QOS 
Get-SFVolume | Set-SFVolume -MinIOPS 100 -MaxIOPS 200 -BurstIOPS 300 -Confirm:$false

#get selected sf volumes with a common naming convention starting with esx
Get-SFVolume esx\* | Set-SFVolume -MinIOPS 100 -MaxIOPS 200 -BurstIOPS 300 -Confirm:$false

#get selected sf volumes based on volume ID
Get-SFVolume -VolumeID (1..5)| Set-SFVolume -MinIOPS 100 -MaxIOPS 200 -BurstIOPS 300 -Confirm:$false

Get-SFVolume -VolumeID (1,5)| Set-SFVolume -MinIOPS 100 -MaxIOPS 200 -BurstIOPS 300 -Confirm:$false

Let me know if you want a more specific example.
