### ISSUE TITLE
[Linux]: Get-SFConfig can't detect existing connection

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#16]
* Ubuntu 16.04 client with PS 6 alpha 15 + SF PS Tools 1.3.0.124 + Element OS 8.6 API endpoint
* This doesn't work, but other commands do (I'm using -version 8).

```
PS /home/sean> Get-SFConfig -verbose                                                                         
VERBOSE: Skipping GetSFConfig command on connection Solidfire
Get-SFConfig : Skipping command on connection Solidfire. CmdLet requires Node connection.
At line:1 char:1
+ Get-SFConfig -verbose
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (SolidFire.Core.Objects.SFConnection:SFConnection) [Get-SFC 
   onfig], ConnectionException
    + FullyQualifiedErrorId : ConnectionError,SolidFire.Node.Get.GetSFConfig
 
```

**Comment by ahaid** [comment]
This error says you should be running this CmdLed on a Node connection. This is the desired functionality. Can you try connecting to a node instead of a cluster and running it again? Use the -Node SwitchParameter on the Connect-SFCluster CmdLet

**Comment by scaleoutsean** [comment]
I see. I misunderstood the meaning of "connection" (I was connected to a node (to Cluster Master via MVIP), but the connection wasn't a Node Connection, it was a Cluster Connection). 
If I tried to repro on v1.2.x I would have realized it too couldn't work, but I now only have 1.3 on both Windows and Linux. I'll try this later and close if it works.

Yep, works fine with v1.3 alpha!
