### ISSUE TITLE
Set-SFDefaultQoS has no examples

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#21]
`get-help Set-SFDefaultQoS -example` doesn't have any examples. 
Maybe not all commands have examples (in which case we can close this), but this is the first case where I noticed this.

**Comment by ArielQuinn** [comment]
Hi Sean! Unfortunately, not all the commands have examples, but we can look into adding that one during our next release as you found a need for it. I'll write out a note for that and put it into our JIRA board. Thank you!

**Comment by scaleoutsean** [comment]
Sounds good. If we can somehow contribute examples, please let me know.
You can close this issue if you think it's enough to have it open in JIRA.
