### ISSUE TITLE
Set-SFVolume IOP levels allowing less values than API

### ISSUE THREAD

**Issue by snoopj123** [solidfire/PowerShell#25]
I know this might be a little on the crazy side, but I was trying to set the MaxIOPS of a volume to > 150,000 using Set-SFVolume.  I get a ParameterBindingValidationException telling me that I can't exceed 100,000.  However, through the API and admin page, I can set this value.  So, is the ParameterBindingValidationException not in tune with the API or just a hard block using the PowerShell module?  I know I get warnings through the admin portal, but it does allow it.

![screen shot 2017-08-08 at 10 58 22 am](https://user-images.githubusercontent.com/11169922/29081567-89cae196-7c28-11e7-9f68-d15e4f7278a5.png)

**Comment by ahaid** [comment]
This is a known bug. The ParameterBindingValidation is limiting the input on MaxIOPS (And MinIOPS and BurstIOPS) to values lower than Element allows, as of 9.0. We have fixed this for our next release and plan to have it out to the community soon. In the meantime, you can use the Invoke-SFAPI CmdLet if you need to create or modify a volume with values outside the current limits.

**Comment by snoopj123** [comment]
Sounds good.  At least Invoke-SFAPI is there.  The last thing I wanted to try to do is have to start using Invoke-WebRequest/Invoke-RestMethod.  Thanks!
