### ISSUE TITLE
connect-sfcluster fails on CentOS 7.3

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#26]
* Version 1.4.0.98
* powershell-6.0.0_beta.2-1.el7.x86_64
* CentOS Linux release 7.3.1611 (Core)

I can ping the MVIP, but Connect-SFCluster fails. From the same PowerShell prompt, I can run `sfcli` and connect to the cluster using the same arguments. I'll re-install to be sure this wasn't a broken installation due to network timeout during download.

```
PS /usr/local/share/powershell/Modules/SolidFire> Connect-SFCluster 1.1.1.1 -Username admin -Password password
Connect-SFCluster : An error occurred during the request.
At line:1 char:1
+ Connect-SFCluster 1.1.1.1 -Username admin -Password password
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Connect-SFCluster], ConnectionException
    + FullyQualifiedErrorId : SolidFire.Core.Exceptions.ConnectionException,SolidFire.Connection.ConnectSFClust
   er

```

**Comment by ahaid** [comment]
1. Is there a chance your client is set to use a different language/localization than English?
2. Will you run $Error[0].Exception.InnerException to pull extra details about the error you received.

**Comment by scaleoutsean** [comment]
Bingo! 
```
PS /usr/local/share/powershell/Modules/SolidFire> $Error[0].Exception.InnerException
The libcurl library in use (7.29.0) and its SSL backend ("NSS/3.21 Basic ECC") do not support custom handling
of certificates. A libcurl built with OpenSSL is required.```
```

Versions: 

* Processing Dependency: libcurl = 7.29.0-35.el7.centos for package: curl-7.29.0-35.el7.centos.x86_64
* Processing Dependency: libcurl for package: powershell-6.0.0_beta.2-1.el7.x86_64

How silly of me - I learned of this issue few months back but since then I forgot how to run that error thing. 

Tried 2 things:

* PS 6 beta 5 + curl 7.55.1 (latest & latest)

```
PS /home/user> $Error[0].Exception.InnerException
The handler does not support custom handling of certificates with this combination of libcurl (7.29.0) and its
SSL backend ("NSS/3.21 Basic ECC").
PS /home/user> curl --version
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.1e zlib/1.2.7 libssh2/1.4.3
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy
```

* PS 6 beta 2 + curl 7.55.1 (recommended & latest)

```
PS /home/user> $Error[0].Exception.InnerException
The libcurl library in use (7.29.0) and its SSL backend ("NSS/3.21 Basic ECC") do not support custom handling
of certificates. A libcurl built with OpenSSL is required.
PS /home/user> curl --version
curl 7.55.1 (x86_64-pc-linux-gnu) libcurl/7.55.1 OpenSSL/1.0.1e zlib/1.2.7 libssh2/1.4.3
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets HTTPS-proxy
```

**Comment by scaleoutsean** [comment]
Today I had a bit of time to take another look. 

If you install or build libcurl-openssl and copy it over the OS libcurl library, Connect-SFCluster works. Also, I used the latest PS Beta 5 to test.

* powershell-6.0.0_beta.5-1.el7.x86_64
* libcurl-openssl-7.43.0-1.1.x86_64

**Comment by ahaid** [comment]
Looks like you got this solved on your own. Please close the issue unless you want us to look into it again.
