### ISSUE TITLE
Wording in error message: Remove-SFDrive: cannot remove driveID XYZ- already available

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#32]
While this message is technically correct it got me confused: `cannot remove driveID 309 - already available`.

Maybe `- already removed` (or `- drive is not active`) would be better. 

Unless the user knows a removed drive is "available" drive, if one doesn't know or forgets, they may wonder why a drive that is in fact available cannot be removed.

```
PS C:\Program Files\SolidFire> Remove-SFDrive -DriveID 309

Confirm
Are you sure you want to perform this action?
Performing the operation "RemoveSFDrive" on target "1.1.1.1 {}".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): A
Remove-SFDrive : xInvalidDriveType: cannot remove driveID 309 - already available
At line:1 char:1
+ Remove-SFDrive -DriveID 309
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (SolidFire.Drive.Remove.RemoveSFDrive:RemoveSFDrive) [Remove
   -SFDrive], Exception
    + FullyQualifiedErrorId : 0,SolidFire.Drive.Remove.RemoveSFDrive
PS C:\Program Files\SolidFire> Get-SFDrive -DriveID 309

```

**Comment by ahaid** [comment]
That error message is sent from the API. The SDK and PowerShell module pass all API errors straight to the user. We don't want to catch and translate every possible error the API can give so we don't translate any of them. If it's terribly bothersome, I can open a ticket on the Element team asking them to change it but I'm not going to make any changes to PowerShell.

**Comment by scaleoutsean** [comment]
I'd appreciate if you could ask them to take a look at this page, and they can decide whether they want to change anything in the API or not., so you don't need to follow up or do anything in particular. (I'd like to see the message improved, but it's not a big deal). 

For the purpose of this GH project, I'll close this now.
