### ISSUE TITLE
Switch to set console color scheme (usability enhancement)

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#33]
The default color scheme looks good, but since the text scheme changed to black + blue, it's became harder to see what's going on when the screen is shared using a projector or lower resolution video recording.

I can right-click on the PS Tools console to change colors of background and foreground text, but keyed in commands are still yellow-on-black. 

![image](https://user-images.githubusercontent.com/16622642/31532895-7974edc2-b022-11e7-892e-7e3ca365ad02.png)

Can we add a switch to the initialize environment script to load a simpler color scheme?

**Comment by ahaid** [comment]
Sean,

Color settings are a personal thing so it's not something I can force when our PowerShell module is installed. However, I feel your pain. I've had to come up with a way to do demos with a dark on light theme. Here's what I do. Put the following into your C:\Users\\[username]\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 file:

    console = $host.UI.RawUI
    console.backgroundcolor = "white"
    console.foregroundcolor = "black"
    $colors = $host.PrivateData
    $colors.VerboseForegroundColor = "white"
    $colors.VerboseBackgroundColor = "blue"
    $colors.WarningForegroundColor = "yellow"
    $colors.WarningBackgroundColor = "darkgreen"
    $colors.ErrorForegroundColor = "red"
    $colors.ErrorBackgroundColor = "white"

    Remove-Module PSReadline

This will set up your PowerShell console to be much more readable on a white background. When you're done, either comment out these lines or rename the file.

One of the key statements above is "Remove-Module PSReadline". That's the thing that keeps turning the commands yellow as you type them.

**Comment by scaleoutsean** [comment]
Thanks, Adam!

> Color settings are a personal thing so it's not something I can force when our PowerShell module is installed. 

Yes of course. I meant letting the user choose on the fly, such as:
`.\Initialize-SFEnvironment.ps1 -BackgroundColor white -ForegroundColor blue`
That would make it easy to initialize (and revert to defaults) without leaving or restarting our SF PS Tools.
But the proposed approach is fine for my personal needs; I'll use that so I'll close this issue.
