### ISSUE TITLE
connect-sfcluster fails on Windows 2016 / Region Format other as English

### ISSUE THREAD

**Issue by mschindl** [solidfire/PowerShell#34]
Windows 2016 (OS: English; **Region Format: German (Germany)**) 
SolidFire PowerShell version 1.4.0.98
SolidFire Element 10.0.0.282

I can ping the MVIP, but Connect-SFCluster fails (with the "false" region setting).

After change of "Region Format" to English (United States) PowerShell works well, but it's not allowed, because of to many workflows on the management server. Is there a fix for that issue available?

![win-powershell](https://user-images.githubusercontent.com/26382876/31618902-82a473a4-b293-11e7-8b24-81205f27b042.png)

**Comment by ahaid** [comment]
This has been fixed in the 1.5 version which is due to release this month. Watch this repository to be notified of the new release as soon as it happens. If you would like to use the RC before it is released, send an email to me at adam.haid@netapp.com.

**Comment by ahaid** [comment]
The 1.5 version was released on Nov 29 and this problem was fixed in it.
