### ISSUE TITLE
SFDrive actions: add filtering parameter(s)?

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#36]
Typical record from JSON output:
```
{
"attributes" : {},
"capacity" : 299917139968,
"driveID" : 35,
"nodeID" : 5,
"serial" : "scsi-SATA_INTEL_SSDSA3CW6CVQR121502R3500FGN-part2",
"slot" : 0,
"status" : "active",
"type" : "volume"
}
```
NodeID seems like an obvious choice of filtering criteria, but to my surprise it's not available.

`Get-SFDrive [[-DriveID] <long[]>] [-Target <string[]>] [-SFConnection <SFConnection[]>] [<CommonParameters>]`

Can NodeID be added to Get- and Remove-SFDrive? 
Use case is to get info on disks in specific node(s). 
Say I wanted to evacuate (remove) disks from NodeID 6.

**Comment by ahaid** [comment]
I created JIra story SDK-929 to address this RFE.

**Comment by arjun960** [comment]
@scaleoutsean We have addressed and resolved this issue and the fix will be available in the next SDK release.
