### ISSUE TITLE
Examples need to be overhauled

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#48]
Examples are in some cases repetitive and in others don't even work (I've fixed 1-2, and I just realized there are more bugs, see below).

I'd prefer to delete all examples from this repo (and leave the essential README-level stuff - see our Python CLI, for an example) and create a new repo with non-essential examples, so that we don't burden Adam with PRs for stuff which he can't verify or doesn't have time to check. 

Thoughts? 

To-Do list of problematic or failing examples is below, I'll update it as I find new issues and fix them.

1) Resulting VAG is empty. 
https://github.com/solidfire/PowerShell/blob/1.5/Sample%20Scripts%20-%20Volumes.ps1#L18

2) Incorrect selection (VolumeName instead of Name) in Getting Started 1.3.
https://github.com/solidfire/PowerShell/blob/1.5/Getting%20Started/Getting%20Started%202015%20-%20Section%201.3%20-%20Modifying%20SolidFire%20Objects.ps1#L48

3) Datastore resizing isn't broken any more.
https://github.com/solidfire/PowerShell/blob/1.5/Getting%20Started/Getting%20Started%202015%20-%20Section%201.3%20-%20Modifying%20SolidFire%20Objects.ps1#L63

4) Get-iSCSI Depth fails (ESXi hostname string to array element conversion)
https://github.com/solidfire/PowerShell/blob/1.5/VMware/PowerActions/Get-iSCSI-Adapter-Queue-Depth-PowerAction.ps1#L16 ; similar bug exists in https://github.com/solidfire/PowerShell/blob/1.5/SPBM/Get-SFVolumeFromDatastore.ps1#L40

5) Remove-SolidFire-Volume-From-VMware.ps1: doesn't work because one of the modules used appears to be missing
https://github.com/solidfire/PowerShell/blob/1.5/VMware/Remove-SolidFire-Volume-From-VMware.ps1#L2

6) Incorrect parameter used ESXi-Host-to-VolumeAccessGroup-Mapping.ps1 - `-Value $vag.VolumeAccessGroupName` should be `-Value $vag.Name`
https://github.com/solidfire/PowerShell/blob/1.5/VMware/ESXi-Host-to-VolumeAccessGroup-Mapping.ps1#L43

7) SolidFire-SPBM fails due to invalid operation in `SolidFire.Core.Objects.SFVolume`
https://github.com/solidfire/PowerShell/blob/1.5/SPBM/SolidFire-SPBM.psm1#L66

8) Script has reference to external module and additionally uses Windows-style path (i.e. it can't work on Linux)
https://github.com/solidfire/PowerShell/blob/1.5/VMware/PowerActions/Set-SFVolumeAttribute-PowerAction.ps1#L33

9) DSNRO and some default values are mentioned in the context of ESXi 6.x, but this parameter has been deprecated since ESXi 5.5. 
https://github.com/solidfire/PowerShell/blob/1.5/VMware/Set-SFVMwareBestPractices.ps1#L147

10) Load-balancing policy is RR which is against the current recommendation from NetApp SolidFire Storage for Microsoft Windows Configuration Guide (Released 2/6/2017).
https://github.com/solidfire/PowerShell/blob/1.5/Microsoft/3-iSCSIConfiguration-v2.ps1#L110

**Comment by ahaid** [comment]
This entire repo needs to be re-evaluated. It works for non-essential examples or to get started on some custom work but it's not supported by the Host Integrations team. I appreciate all your help @scaleoutsean but you're right, I can't keep up with issues here. In true open source fashion, I'd suggest you keep sending PRs and I'll merge them right away. I'll trust you and other contributors to verify your changes until we establish a different way to provide this service.

**Comment by arjun960** [comment]
@scaleoutsean We have addressed and resolved this issue and the fix will be available in the next SDK release.
