### ISSUE TITLE
CreateCluster: This node not specified in ensemble

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#55]
* EOS 10.1.0.283
* SF PST 1.5.0.119
* Below, 56.x is 10G, and 59.x is 1G interface

```
PS /home/sean> New-SFCluster -Mvip 192.168.59.60 -Svip 192.168.56.56 -Username admin -Password p@ss -Nodes "192.168.59.61","192.168.59.62","192.168.59.63","192.168.59.64" -AcceptEula:$True                   
New-SFCluster : xSelfNotInEnsemble: This node not specified in ensemble mCip=192.168.56.51
At line:1 char:1
+ New-SFCluster -Mvip 192.168.59.60 -Svip 192.168.56.56 -Username hciadmi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidResult: (SolidFire.Cluster.New.NewSFCluster:NewSFCluster) [New-SFCluster], Exception
+ FullyQualifiedErrorId : 0,SolidFire.Cluster.New.NewSFCluster
```
In this case, something unusual happened in Element OS  Web UI - although I picked 1G as the Management Interface and set gateway only on 1G interfaces, the Web UI detected all cluster member candidates using their 10G NIC (bug, perhaps?). Unlike the Web interface, PowerShell tools doesn't auto-identify the management interface.

So while the Web UI can get around its own issue, SolidFire PowerShell tools (possibly solidfire-cli too?) fails when 1G IPs are specified (the above error), so one has to help it by specifying 10G NICs.

According to the SF Element OS 10.1 UG, createCluster's nodes array ought to accept "CIP/SIP addresses", which I take to mean either 1G or 10G IPs.

**Comment by ahaid** [comment]
The PowerShell utility doesn't translate any of the inputs or outputs of the API for the CreateCluster method. This issue likely exists in the API. We will watch for it and see if it's appropriate to alter it there.
