### ISSUE TITLE
connect-sfcluster fails on CentOS 7.4

### ISSUE THREAD

**Issue by eggzotic** [solidfire/PowerShell#56]
Hi all, pretty similar to another issue where Sean had issues with connect-SFCluster on CentoOS 7.3. However the cause may be different as the libcurl symptons don't show here:

PS /home/oracle> Connect-SFCluster -Target 172.16.13.88

cmdlet Connect-SFCluster at command pipeline position 1
Supply values for the following parameters:
(Type !? for Help.)
Credential
User: hciadmin
Password for user hciadmin: **********

Connect-SFCluster : Unable to connect to endpoint: https://172.16.13.88/json-rpc/7.0. An error occurred during the request.
At line:1 char:1
+ Connect-SFCluster -Target 172.16.13.88
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-SFCluster], ConnectionException
+ FullyQualifiedErrorId : SolidFire.Core.Exceptions.ConnectionException,SolidFire.Connection.ConnectSFCluster

PS /home/oracle> $Error[0].Exception.InnerException
An error occurred during the request.

Hopefully something known? From the same subnet, and a Windows VM, the connection to the same cluster works fine, just FYI.

Richard.

**Comment by ahaid** [comment]
This is a known issue and we have a hotfix in the works. We are running it through tests now. This is likely the same libcurl problem. Go one step deeper in the exception stack to find the problem.

    $Error[0].Exception.InnerException.InnerException

We will have a hotfix as soon as we can. In the meantime, this version should still work on ubuntu 14.04+.

**Comment by eggzotic** [comment]
Great, thx for the update Adam. I'll dig up that extra info when I'm back from leave - sorry bad timing - just raise an issue and don't hang round to troubleshoot it properly(!)

**Comment by ahaid** [comment]
With the 1.5.1 hotfix released last week, this should work now. run `Import-Module SolidFire.Core` to bring in the newest module. More installation instructions are available [here](https://github.com/solidfire/PowerShell/blob/master/docs/linux/README.md).

**Comment by scaleoutsean** [comment]
I happened to try it today on v7.0, it can connect:

* CentOS 7 (3.10.0-123.el7.x86_64)
* PS v6.1.0-preview.1
* SolidFire.Core v1.5.1.1

Don't know if 7.4 is OK, I have to keep this CentOS on v7.0.

**Comment by ahaid** [comment]
Glad to hear. Closing the issue.
