### ISSUE TITLE
Import-Module on CentOS works differently from Ubuntu

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#57]
IIRC on Debian-like distros `Import-Module SolidFire.Linux` is required to load the SF PS module.

But on CentOS 7 (3.10.0-123.el7.x86_64), that doesn't work and `Import-Module SolidFire` does - the opposite from Debian. On CentOS 7 Import-Module SolidFire-Linux generates this error:

```
Connect-SFCluster : Could not load file or assembly 'System.Net.Http.WebRequest, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
At line:1 char:1
+ Connect-SFCluster 1.1.1.1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Connect-SFCluster], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,SolidFire.Connection.ConnectSFCluster
```
Or maybe this is something that changed in recent Powershell editions.

My Powershell package: 6.1.0~preview.1-1.rhel.7

**Comment by ahaid** [comment]
With the 1.5.1 hotfix released last week, this should work now. run `Import-Module SolidFire.Core` to bring in the newest module. More installation instructions are available [here](https://github.com/solidfire/PowerShell/blob/master/docs/linux/README.md).

**Comment by scaleoutsean** [comment]
After upgrade to v1.5.1.1, `Import-Module SolidFire.Core` works for me on Ubuntu 16.04. Feel free to close this issue.
