### ISSUE TITLE
User Guide: Trivial change required to obtain command listing on Linux

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#58]
UG 1.5.1.1 page 3 fixes the get-command example, but now there's a similar problem in the improved section ;-) 
My guess: if American punctuation rules are used, `.)` is probably fine, but in that case `.).` should be changed to `.)` 
Right now it appears as if the example uses `-Module SolidFire.Core.` because of the extra period after the bracket.

![image](https://user-images.githubusercontent.com/16622642/38869084-1151339e-427c-11e8-85d5-7687732cd875.png)

**Comment by Salmanius** [comment]
I forwarded this to our technical writer. In the guide coming with 1.6 he changed it to no longer be surrounded by parenthesis so this problem is solved. Thanks for pointing it out Sean, should prevent any C+P issues.
