### ISSUE TITLE
Connect-SFCluster doesn't always mask the password

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#59]
I noticed this few months ago, but I didn't quite understand what I was seeing. 

* `Connect-SFCluster 1.0.0.1 -Username admin`
* PS Tools v1.5.1.1, PSVersion 6.1.0-preview.1, Ubuntu 16.04.4 LTS

![image](https://user-images.githubusercontent.com/16622642/38933589-01427fbe-434c-11e8-94d7-e637c7f32f26.png)

**Comment by ahaid** [comment]
Ah yes. You've hit the situation where the username is passed in via parameter but not the password. The prompt for password changes to a String from a SecureString in that situation. It's a known thing and there's nothing I can do about it with the available parameter types from PowerShell. The hope is that people will input the password at the same time as the username in either the parameter list or entered in the credential dialog.
