### ISSUE TITLE
set-SFVolume SetCreateTime

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#61]
`set-SFVolume -VolumeID 5 -SetCreateTime "2019-01-10T06:51:55Z" -Confirm:$false`

This command completes without error although it probably shouldn't work at all. (The value doesn't actually change, thankfully.)

Volume Object shows `string CreateTime {get;set;}` which indicates SetCreateTime should work and the cmdlet does work, so it seems a case of misdocumented access modifier. Or do these access modifiers don't indicate what I think they indicate?

**Comment by ahaid** [comment]
We're going to remove this unused parameter in v1.6
