### ISSUE TITLE
Unnecessary (?) output in Remove-SFSnapshot

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#63]
`Remove-SFSnapshot` outputs possibly unnecessary details. 

Consider `Get-SFSnapshot -VolumeID 111 | Remove-SFSnapshot -Confirm:$false`. This output a list of all cluster snapshots and at first made me think I mistakenly wiped all snapshots from other volumes/users.

I am not sure if it's useful to see a list of all (unrelated) snapshots in the output of Remove-SFSnapshot - I can't think of a good reason, but maybe there is one.

**Comment by ahaid** [comment]
Thanks for the heads up. We will look at adjusting this in the next release.

**Comment by arjun960** [comment]
@scaleoutsean  We have addressed and resolved this issue and the fix will be available in the next SDK release.
