### ISSUE TITLE
Network-related VAG params don't seem to work

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#64]
`VirtualNetworkID` and `VirtualNetworkTags` don't seem to work. I can "set" them but I can't "get" them so I suspect they don't actually get saved. I also can't see how to do the same in the UI so I'm guessing these aren't supposed to be available?

* PS: 5.1 on Win 10
* SF Module: 1.5.0.119

**Comment by ahaid** [comment]
Which cmdlet are you referring to?

**Comment by scaleoutsean** [comment]
Hah - you got a point there. :-)

I meant Set and Modify SFVirtualAccessGroup.

**Comment by Salmanius** [comment]
Thanks for letting us know. We will try to get this in with the 1.6 release.

**Comment by arjun960** [comment]
@scaleoutsean We have removed the parameters virtualNetworkID and virtualNetworkTags from the New-SFVolumeAccessGroup and Set-SFVolumeAccessGroup commandlets. The changes for the same will be reflected in the next SDK release.

Also, Changes related to references of the above said parameters in the powershell documentation will also be reflected in the SDK release.
