### ISSUE TITLE
Get-VMHost seems not present

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#7]
Here `Get-VMHost` is mentioned:
https://github.com/solidfire/PowerShell/blob/master/Getting%20Started/Getting%20Started%202015%20-%20Section%203%20-%20Reporting.ps1#L62

But the command doesn't seem to work for me and also it's not listed in `Get-SFcommand` output.

**Comment by joshatwell** [comment]
Get-VMHost is a VMware PowerCLI cmdlet. I can update the file to specify that PowerCLI commands are included in the exercise.
You can download PowerCLI from VMware at http://www.vmware.com/go/powercli
