### ISSUE TITLE
Powershell module 1.5.0.119 fails to parse async delay data if populated in the json payload response to Get-SFvolumeStats

### ISSUE THREAD

**Issue by ddansf** [solidfire/PowerShell#70]
Initiating get-sfvolumestats in Powershell tools 1.5.0.119 against a 10.4 AFA cluster which has volumes replicating in Asynchronous mode yields:

 PS C:\Program Files\SolidFire> Get-SFVolumeStats
Get-SFVolumeStats : JsonSerializationException: Error converting value "00:00:00.000000" to type
'System.Nullable`1[System.Int64]'. Path 'result.volumeStats[0].asyncDelay', line 1, position 94.
At line:1 char:1
Get-SFVolumeStats
CategoryInfo          : InvalidResult: (SolidFire.Volume.Get.GetSFVolumeStats:GetSFVolumeStats) [Get-SFVolumeStats], Exception
 FullyQualifiedErrorId : 0,SolidFire.Volume.Get.GetSFVolumeStats
 PS C:\Program Files\SolidFire>
 

The same request is successful on a 10.4 cluster without any volumes replicating in asynchronous mode, as is a request from module 1.3.1.4's against clusters with or without volumes in asynchronous replication.

Example json output from ListVolumeStatsByVolume method (assuming that's the correct underlying method):

"asyncDelay":"00:00:00.000000"

**Comment by Salmanius** [comment]
Hello Dan, Thank you for submitting this issue to us. It seems like this is a case of bad type converting. Currently we do not have any time to fix this issue in this PI, but when we do, this should be an easy fix in the 1.6 release of our PowerShell Module.

**Comment by ntavendale** [comment]
This appears to be caused by the Powershell cmdlets using the dotnet sdk built for neon. When using the dotnet sdk built for sodium (which the next release will be) the issue is resolved.
Have tested with next release using the sodium sdk and it works as expected with volumes replicating in sync mode.
