### ISSUE TITLE
Should cluster admin accounts be case sensitive? 

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#73]
* PS 6.1.2
* SF 1.5.1.1

After I add the cluster admin account `DirkD`

```
PS /home/sean> Connect-SFCluster 192.168.1.30 -Username DirkD -Password B00GInites                        
...
PS /home/sean> Connect-SFCluster 192.168.1.30 -Username dirkd -Password B00GInites 
Connect-SFCluster : Unable to connect to endpoint: https://192.168.1.30/json-rpc/7.0. 
```

In that case I'd expect this to work, because `DirkD` and `dirkd` would be different accounts with different AccountID's, but:

```
PS /home/sean> New-SFClusterAdmin -Username dirkd -AcceptEula:$true -Password 123123123 -Access reporting
New-SFClusterAdmin : xDuplicateUsername: xDuplicateUsername
```

**Comment by Salmanius** [comment]
Hi Sean, unfortunately this is a limitation on the element side. We only pass the data to and from so we are unable to effect this behavior.

**Comment by scaleoutsean** [comment]
All right, that's fine as long as it's documented (somewhere). 
Maybe it already is, but in the online help and few other places I looked I couldn't find anything about case sensitivity. 

Ideally either in `-full` help for each *SFClusterAdmin cmdlet or in http://solidfire.github.io/sdk-dotnet/help/html/P_SolidFire_Element_Api_ClusterAdmin_Username.htm

**Comment by Salmanius** [comment]
I think that is a completely fair ask. I'll add it to our things to do for the 1.6 release.

**Comment by arjun960** [comment]
@scaleoutsean Help of New-SFclusterAdmin is updated which explicitly mentions that "Username is not case sensitive" and change is available in the SDK12.3 release. So closing the issue.
