### ISSUE TITLE
Missing closing double quote in Set-SFClusterConfig help

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#76]
* SolidFire.Core 1.5.1.1
* PowerShell 6.1.2

```
    -------------------------- EXAMPLE 1 --------------------------
    
    PS C:\>Set-SFClusterConfig -Name "Node1" -Cluster "TestCluster
    
```

**Comment by arjun960** [comment]
Issue fixed. Please upgrade SolidFire.Core to latest version (https://www.powershellgallery.com/packages/SolidFire.Core/12.3.0.81) to see the change. Closing the issue.
