### ISSUE TITLE
Start-SFClusterPairing truncates output (pairing key)

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#8]
Here's the output I get with v1.2.1.1

```
7b22636c7573546572506169724944223a142c22636c7573a4657250616972555c4944223a223431653e396566392d346630352d3436653...
```

**Comment by ahaid** [comment]
The Start-SFClusterPairing cmdlet is returning a [StartClusterPairingResult](http://solidfire.github.io/sdk-dotnet/help/v1.0/html/T_SolidFire_Element_Api_StartClusterPairingResult.htm) object which has two properties, ClusterPairID and ClusterPairingKey. If you specify the ClusterPairingKey should be used in the Complete-SFClusterPairing CmdLet, it will not be truncated. 

For full details of this (and all) cmdlets, run `Get-Help Start-SFClusterPairing -full` and you'll see the OUTPUTS section points you to the SDK documentation for the return type of that CmdLet.
