### ISSUE TITLE
Case-sensitive error with volumeAccessGroupID parameter

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#80]
When ModifyVolumeAccessGroup is called with `Invoke-SFApi`, `volumeAccessGroupID` parameter is case sensitive: `VolumeAccessGroupID` (edit: with SF PS Tools on Linux) results in a missing parameter error because VolumeAccessGroupID isn't recognized. 

```powershell
Invoke-sfapi : Missing member=[volumeAccessGroupID] members=
{VolumeAccessGroupID,deleteOrphanInitiators,initiators,requestAPIVersion}
```

**Comment by arjun960** [comment]
@scaleoutsean When using Invoke-SFApi, to send parameter we have to always mention parameters in camel Casing/in the format (generic json input format) mentioned in the description of [API](https://docs.netapp.com/sfe-120/index.jsp?topic=%2Fcom.netapp.doc.sfe-api%2FGUID-4F50E28E-D29D-44DB-A7A5-F1735C873449.html&resultof=%22%4d%6f%64%69%66%79%56%6f%6c%75%6d%65%41%63%63%65%73%73%47%72%6f%75%70%22%20%22%6d%6f%64%69%66%79%76%6f%6c%75%6d%65%61%63%63%65%73%73%67%72%6f%75%70%22%20). 

Will update the help of Invoke-SFApi accordingly. The change can be seen in next SDK release.

**Comment by arjun960** [comment]
@scaleoutsean updated the help of Invoke-SFApi as discussed above. The changes will be available in the next SDK release.

So, closing the issue.
