### ISSUE TITLE
Inconsistent SFConnection pipe behavior across cmdlets

### ISSUE THREAD

**Issue by ddansf** [solidfire/PowerShell#84]
When connected to 2 SF Clusters at the same time, some cmdlets do not pipe SFConnection parameter passthrough to the next cmdlet. 
 
Example Scenario:

$Sourcecluster = Connect-SFCluster -Target <Clustername>
$Destination = Connect-SFCluster -Target <Clustername>

Example Command:

Get-SFVolumePair -SFconnection <sourcecluster> | Remove-SFVolume

In the above command, Remove-SFVolume removes volumes from the $Destination cluster instead of the intended $Sourcecluster because the SFConnection value is not piped from Get-SFVolumePair to Remove-SFVolume as expected (given that other cmdlets do pipe the SFConnection value).

The workaround for the above is to explicitly use SFConnection in the Remove-SFVolume cmdlet, e.g., Get-SFVolumePair -SFconnection <sourcecluster> | Remove-SFVolume -SFconnection <destination cluster>.

The ask is to make pipe redirection behavior around the SFConnection value consistent across cmdlets to avoid confusion.

**Comment by scaleoutsean** [comment]
Similar issue in https://github.com/solidfire/PowerShell/issues/77

**Comment by ntavendale** [comment]
Is it the Target, the SFConnection, or both that needs to be piped through?

**Comment by scaleoutsean** [comment]
> In the above command, Remove-SFVolume removes volumes from the $Destination cluster instead of the intended $Sourcecluster

Remove-SFVolume has no connection specified and $Destination is the most recent (current) connection, so that behavior looks logical to me.

**Comment by ntavendale** [comment]
I believe the behaviour is logical also. Generally you pipe the _output_ of one command into the input of another so, unless Get-SFVolumePair outputs an SF-Connection object, there is no connection to pipe to the second command, meaning it will need to be explicitly passed in as a parameter.
