### ISSUE TITLE
Get-SFIscsiConnections doesn't populate AccountID and AccountName

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#85]
With SF PS Tools v1.5.1 and EOS 11.7 `Get-SFIscsiConnections` incorrectly populates AccountID and doesn't populate AccountName

```
"AccountID" = 0
"AccountName" = ""
```
ListIscsiSessions does work correctly.

**Comment by arjun960** [comment]
@scaleoutsean Yeah, ListISCSISessions doesn't populate AccountID and AccountName. Bug is created at element side to investigate this and the fix will be available in the future element releases. Will update here once the fix is available.

**Comment by arjun960** [comment]
@scaleoutsean After further investigation and analysis, found that ListISCSISessions does populate AccountID and AccountName only when Account-Based Chap is used to connect to the volumes. It displays accountID and accountName as empty values when no authentication or initiator-based chap is used.

Please refer below screenshot:
![image](https://user-images.githubusercontent.com/75774349/157488056-171720da-688c-496a-b5e7-dc2584377666.png)
