### ISSUE TITLE
Return consistent object type with Get-ActiveNode 

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#93]
Get-SFActiveNode seems to return different object types depending on situation:

- SolidFire.Core.RpcBase
- System.Array

The second one is what we'd expect, the first one is when we have SF Demo VM i.e. single node cluster. There, instead of an array, we get this "custom object". 

I'd prefer to get System.Array in both cases, so that I don't have to do if-else.

**Comment by arjun960** [comment]
The Get-SFactivenode return object type will be System.Array only when it is returning a list of nodes to console. In every case of returning single node, its return object type is SolidFire.Core.RpcBase.

If the command is returning a list of nodes, it will enumerate the collection and return node objects on console. and if its returning only one node, it again returns node object. In either case, we get objects of type "Node".
