### ISSUE TITLE
Error on Invoke-SFShutdown - xUnknownException: map::at

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/PowerShell#94]
```
PS /> Invoke-SFShutdown  -Option halt -NodeID 0 
WARNING: The following connection(s) will be shutdown and unavailable: DR

VERBOSE: Running Invoke_SFShutdown command on connection PROD at https://192.168.1.30/json-rpc/12.5 with username admin

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): y
Invoke-SFShutdown: xUnknownException: xUnknownException: map::at

```

- PowerShell 7.3.6
- SolidFire Core 12.3.0.81
- Ubuntu 22.04 LTS

I think the same combo of SolidFire v12 API, SolidFire.Core module and Ubuntu used to work before. Could it be related to something that changed in PowerShell 7.3, maybe?

**Comment by arjun960** [comment]
Hi @scaleoutsean It's neither Powershell issue nor Solidfire Core module issue. Its just that NodeID "0" is not present in the cluster - A better exception message would really avoid the confusion here. Will do the changes accordingly.

**Comment by scaleoutsean** [comment]
Huh... that's funny! 

I don't understand how I had avoided falling into this trap before.

Either it's because I hadn't use it for a while and simply lost the habit, or seeing `0` here made me mindlessly enter 0 instead of 1 (I know 0 stands for first list member).

![image](https://github.com/solidfire/PowerShell/assets/16622642/e766152a-9cbf-4b7e-b341-13f555941d9f)

But that aside, error handling in this particular command does seem subpar, e.g. in this command it is handled properly.

```pwsh
PS /home/sean> Get-SFNodeStats -NodeID 0
Get-SFNodeStats: xNodeIDDoesNotExist: Node 0 does not exist.
PS /home/sean> Get-SFNodeStats -NodeID 1

CBytesIn                  : 2157749699
CBytesOut                 : 202981019
...
```

**Comment by arjun960** [comment]
Agree!! Will make the necessary changes to give a proper error message. The changes will be available in the next SDK release.

So, closing the issue.
